# Generated by Django 5.1.1 on 2025-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='posts/images/'),
            preserve_default=False,
        ),
    ]
